const chatListTypes = {
  START_CHAT: "START_CHAT",
  SELECT_CHAT: "SELECT_CHAT",
  ADD_SENT_MESSAGES_TO_CONTACT: "ADD_SENT_MESSAGES_TO_CONTACT",
  ADD_RECEIVED_MESSAGES_TO_CONTACT: "ADD_RECEIVED_MESSAGES_TO_CONTACT",
};

export default chatListTypes;
